// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Transaction<T = Array<string>> = { id: number, error: boolean | null, er_message: string | null, created_at: string, data: T | null, };
